apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml

patches:
- patch: |-
    - op: add
      path: /spec/rules/-
      value:
        host: hello-kustomize.net
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: hello-kustomize
                  port:
                    number: 8000
  target:
    kind: Ingress
