apiVersion: v1
kind: Service
metadata:
  name: hello-kustomize
  labels:
    name: hello-kustomize
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
  selector:
    name: hello-kustomize
