apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - env:
          - name: DB_USER
            value: dbuser
        image: hello-world
        name: hello-world
        ports:
        - containerPort: 8000
