resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DB_PASSWORD
          value: staging-password
    target:
      kind: Deployment
      name: hello-world
