---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  selector:
    matchLabels:
      name: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - name: hello-world
          image: hello-world
          ports:
            - containerPort: 8000
